name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      env:
        SECRET_KEY: test_secret_key_for_ci
        DATABASE_URL: sqlite:///:memory:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GPT_MODEL: gpt-3.5-turbo
      run: |
        cd backend
        pytest tests/ --tb=short -v
    
    - name: Generate coverage report
      env:
        SECRET_KEY: test_secret_key_for_ci
        DATABASE_URL: sqlite:///:memory:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GPT_MODEL: gpt-3.5-turbo
      run: |
        cd backend
        pytest tests/ --cov=app --cov-report=xml --cov-report=term
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        fail_ci_if_error: false